version: '3.4'

networks:
  frontend:
  monitoring:

volumes:
  prometheus:
  alertmanager:

configs:
  prom_config:
    file: ./prometheus/prometheus.yml
  alert_rules:
    file: ./prometheus/alerts.yml
  alertmanager:
    file: ./alertmanager/alertmanager.yml

services:
  orbiter:
    image: gianarb/orbiter:d2c82ad
    command: daemon
    networks:
      - monitoring
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.role == manager
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
  app:
    image: dockercloud/hello-world:latest
    labels: [orbiter=true]
    networks:
      - frontend
      - monitoring
    environment:
      - SERVICE_PORTS=80
      - VIRTUAL_HOST=*
    deploy:
      mode: replicated
      replicas: 1
      labels: [orbiter=true]
      update_config:
        parallelism: 1
        delay: 3s
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      restart_policy:
          condition: on-failure
          delay: 3s
          max_attempts: 3
          window: 5s
  lb:
    image: dockercloud/haproxy:1.6.7
    networks:
      - frontend
      - monitoring
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
    depends_on:
      - web
    environment:
      - ADDITIONAL_SERVICES=project_dir:web
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 3s
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      restart_policy:
          condition: on-failure
          delay: 3s
          max_attempts: 3
          window: 5s
  prometheus:
    image: prom/prometheus:v2.1.0
    networks:
      - monitoring
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - prometheus:/data
    configs:
      - source: prom_config
        target: /etc/prometheus/prometheus.yml
      - source: alert_rules
        target: /etc/prometheus/alerts.yml
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
  haproxy_exporter:
    image: prom/haproxy-exporter:v0.9.0
    networks:
      - monitoring
    command:
      - '--haproxy.scrape-uri=http://stats:stats@lb:1936/haproxy?stats;csv'
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
  alertmanager:
    image: prom/alertmanager:v0.13.0
    networks:
      - monitoring
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    volumes:
      - alertmanager:/data
    configs:
      - source: alertmanager
        target: /etc/alertmanager/alertmanager.yml
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
  unsee:
    image: cloudflare/unsee:v0.9.1
    networks:
      - monitoring
    environment:
      - "ALERTMANAGER_URIS=default:http://alertmanager:9093"
    ports:
      - 8080:8080
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
  grafana:
    image: grafana/grafana:4.6.3
    networks:
      - monitoring
    ports:
      - 3000:3000
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 256M
